import { COLORS } from "@utils/constants.utils";
import { Variants } from "framer-motion";
export const cursorMotionVariants = (posX: number, posY: number) => {
  let variants: Variants = {
    visible: { opacity: 0 },
    hidden: { opacity: 0 },
    default: {
      opacity: 1,
      left: 0,
      top: 0,
      x: posX - 10 + "px",
      y: posY - 10 + "px",
      height: 15,
      width: 15,
      backgroundColor: COLORS.primary,
      mixBlendMode: "difference",
      border: `0px solid ${COLORS.primary}`,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 30,
        duration: 0.3,
      },
    },
    heading: {
      left: 0,
      top: 0,
      opacity: 1,
      height: 100,
      width: 100,
      x: posX - 50 + "px",
      y: posY - 50 + "px",
      backgroundColor: "#b6a4fc",
      mixBlendMode: "difference",
      border: `0px solid ${COLORS.primary}`,
      transition: {
        type: "spring",
        stiffness: 120,
        damping: 20,
      },
    },
    subheading: {
      left: 0,
      top: 0,
      opacity: 1,
      height: 50,
      width: 50,
      x: posX - 25 + "px",
      y: posY - 25 + "px",
      backgroundColor: "#b6a4fc",
      mixBlendMode: "difference",
      border: `0px solid ${COLORS.primary}`,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 30,
        duration: 0.3,
      },
    },
    navlink: {
      left: 0,
      top: 0,
      opacity: 1,
      height: 70,
      width: 70,
      x: posX - 35 + "px",
      y: posY - 35 + "px",
      backgroundColor: COLORS.cursorBgPrimary,
      backdropFilter: "blur(1px)",
      WebkitBackdropFilter: "blur(1px)",
      color: COLORS.primary,
      transition: {
        type: "spring",
        stiffness: 200,
        damping: 30,
        duration: 0.6,
      },
    },
    navlinkIcon: {
      left: 0,
      top: 0,
      x: posX - 3 + "px",
      y: posY - 3 + "px",
      opacity: 1,
      scale: 1,
      height: 6,
      width: 6,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 30,
        duration: 0.3,
      },
    },
    heroAction: {
      left: 0,
      top: 0,
      opacity: 1,
      height: 90,
      width: 90,
      x: posX - 45 + "px",
      y: posY - 45 + "px",
      backgroundColor: COLORS.cursorBgPrimary,
      backdropFilter: "blur(2px)",
      WebkitBackdropFilter: "blur(2px)",
      mixBlendMode: "initial",
      color: COLORS.primary,
      border: `1px solid ${COLORS.primary}`,
      transition: {
        type: "spring",
        stiffness: 300,
        damping: 30,
        duration: 0.3,
      },
    },
  };

  return variants;
};

export const cursorSpanMotionVariants: Variants = {
  hidden: { opacity: 0, y: 100 },
  visible: { opacity: 1 },
  default: {
    y: 0,
    opacity: 1,
    transition: {
      duration: 0.5,
    },
  },
};
